# ============================================================
# db-init-job.yml - One-time DB initialization Job
# ============================================================
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: capstone
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: db-init
          image: 464813693523.dkr.ecr.us-west-2.amazonaws.com/capstone-flask-app:latest
          command: ["python", "create_db.py"]
          envFrom:
            - configMapRef:
                name: app-config
      restartPolicy: OnFailure
  backoffLimit: 5
